/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessRegisterRouteImport } from './routes/business-register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as VenuePlaceIdRouteImport } from './routes/venue.$placeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegisterRoute = BusinessRegisterRouteImport.update({
  id: '/business-register',
  path: '/business-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuePlaceIdRoute = VenuePlaceIdRouteImport.update({
  id: '/venue/$placeId',
  path: '/venue/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-register': typeof BusinessRegisterRoute
  '/profile': typeof ProfileRoute
  '/venue/$placeId': typeof VenuePlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-register': typeof BusinessRegisterRoute
  '/profile': typeof ProfileRoute
  '/venue/$placeId': typeof VenuePlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-register': typeof BusinessRegisterRoute
  '/profile': typeof ProfileRoute
  '/venue/$placeId': typeof VenuePlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/business-register' | '/profile' | '/venue/$placeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/business-register' | '/profile' | '/venue/$placeId'
  id: '__root__' | '/' | '/business-register' | '/profile' | '/venue/$placeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRegisterRoute: typeof BusinessRegisterRoute
  ProfileRoute: typeof ProfileRoute
  VenuePlaceIdRoute: typeof VenuePlaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-register': {
      id: '/business-register'
      path: '/business-register'
      fullPath: '/business-register'
      preLoaderRoute: typeof BusinessRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$placeId': {
      id: '/venue/$placeId'
      path: '/venue/$placeId'
      fullPath: '/venue/$placeId'
      preLoaderRoute: typeof VenuePlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRegisterRoute: BusinessRegisterRoute,
  ProfileRoute: ProfileRoute,
  VenuePlaceIdRoute: VenuePlaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
